/* The following code was generated by JFlex 1.4.1 on 29/06/16 11:52 */

package compiler.syntax;

import compiler.exceptions.YeledCompilerException;	// excecao do projeto
import java_cup.runtime.Symbol;
import java_cup.runtime.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 29/06/16 11:52 from the specification file
 * <tt>C:/Users/AndreLucas/Downloads/lexer.flex</tt>
 */
public class Lexer implements Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 41,  0,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    40,  8,  0,  0,  0, 13,  0, 38, 20, 21, 11,  9, 22, 10,  4, 12, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 24, 23,  5,  6,  7,  0, 
     0,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 39,  0,  0,  0, 
     0, 14,  2, 35, 16, 30, 28,  2, 29, 27,  2,  2, 31,  2, 15, 17, 
    37,  2, 18, 32, 19, 34, 36, 33,  2,  2,  2, 25,  0, 26,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\5\3"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\7\3"+
    "\1\1\1\0\1\24\1\25\1\26\1\27\1\0\1\30"+
    "\1\31\2\3\1\32\3\3\1\33\6\3\4\0\1\34"+
    "\1\35\2\3\1\36\6\3\1\37\2\0\1\3\1\40"+
    "\1\3\1\41\1\3\1\42\1\43\1\44\2\45\1\3"+
    "\1\46\1\47\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\52\0\52\0\u01a4\0\52\0\52\0\u01ce"+
    "\0\u01f8\0\u0222\0\u024c\0\u0276\0\52\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348"+
    "\0\u0372\0\u039c\0\u03c6\0\322\0\322\0\52\0\52\0\52"+
    "\0\u03f0\0\52\0\u041a\0\u0444\0\u046e\0\176\0\u0498\0\u04c2"+
    "\0\u04ec\0\176\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8"+
    "\0\u0612\0\u063c\0\u0666\0\u0690\0\176\0\176\0\u06ba\0\u06e4"+
    "\0\176\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\52"+
    "\0\u080a\0\u0834\0\u085e\0\176\0\u0888\0\176\0\u08b2\0\176"+
    "\0\176\0\176\0\u0834\0\52\0\u08dc\0\176\0\176\0\176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\4\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\4\1\36\2\4"+
    "\1\37\1\4\1\40\1\41\1\42\1\43\1\2\2\3"+
    "\53\0\1\3\46\0\2\3\2\0\2\4\12\0\6\4"+
    "\7\0\13\4\7\0\1\5\1\44\50\0\1\45\54\0"+
    "\1\46\51\0\1\47\51\0\1\50\1\51\50\0\1\52"+
    "\56\0\1\53\40\0\2\4\12\0\1\4\1\54\4\4"+
    "\7\0\13\4\6\0\2\4\12\0\3\4\1\55\2\4"+
    "\7\0\13\4\6\0\2\4\12\0\4\4\1\56\1\4"+
    "\7\0\13\4\6\0\2\4\12\0\6\4\7\0\3\4"+
    "\1\57\7\4\6\0\2\4\12\0\6\4\7\0\2\4"+
    "\1\60\10\4\6\0\2\4\12\0\1\4\1\61\4\4"+
    "\7\0\1\4\1\62\11\4\6\0\2\4\12\0\6\4"+
    "\7\0\4\4\1\63\6\4\6\0\2\4\12\0\6\4"+
    "\7\0\4\4\1\64\6\4\6\0\2\4\12\0\6\4"+
    "\7\0\2\4\1\65\10\4\6\0\2\4\12\0\6\4"+
    "\7\0\2\4\1\66\10\4\6\0\2\4\12\0\3\4"+
    "\1\67\2\4\7\0\13\4\6\0\2\4\12\0\4\4"+
    "\1\70\1\4\7\0\13\4\6\0\2\71\12\0\11\71"+
    "\1\0\1\71\2\0\13\71\1\0\1\72\1\71\1\0"+
    "\13\73\1\74\36\73\51\53\3\0\2\4\12\0\2\4"+
    "\1\75\3\4\7\0\13\4\6\0\2\4\12\0\5\4"+
    "\1\76\7\0\13\4\6\0\2\4\12\0\5\4\1\77"+
    "\7\0\13\4\6\0\2\4\12\0\6\4\7\0\3\4"+
    "\1\100\7\4\6\0\2\4\12\0\5\4\1\101\7\0"+
    "\13\4\6\0\2\4\12\0\3\4\1\102\2\4\7\0"+
    "\13\4\6\0\2\4\12\0\6\4\7\0\5\4\1\103"+
    "\5\4\6\0\2\4\12\0\6\4\7\0\1\104\12\4"+
    "\6\0\2\4\12\0\1\105\5\4\7\0\13\4\6\0"+
    "\2\4\12\0\6\4\7\0\1\106\12\4\6\0\2\4"+
    "\12\0\1\4\1\107\4\4\7\0\13\4\52\0\1\110"+
    "\22\0\1\71\3\0\1\71\26\0\5\73\1\111\44\73"+
    "\5\0\1\112\5\0\1\74\40\0\2\4\12\0\6\4"+
    "\7\0\7\4\1\113\3\4\6\0\2\4\12\0\1\4"+
    "\1\114\4\4\7\0\13\4\6\0\2\4\12\0\1\115"+
    "\5\4\7\0\13\4\6\0\2\4\12\0\6\4\7\0"+
    "\3\4\1\116\7\4\6\0\2\4\12\0\6\4\7\0"+
    "\4\4\1\117\6\4\6\0\2\4\12\0\4\4\1\120"+
    "\1\4\7\0\13\4\6\0\2\4\12\0\2\4\1\121"+
    "\3\4\7\0\13\4\6\0\2\4\12\0\5\4\1\122"+
    "\7\0\13\4\4\0\5\73\1\123\44\73\5\0\1\124"+
    "\46\0\2\4\12\0\4\4\1\125\1\4\7\0\13\4"+
    "\6\0\2\4\12\0\5\4\1\126\7\0\13\4\6\0"+
    "\2\4\12\0\6\4\7\0\3\4\1\127\7\4\6\0"+
    "\2\4\12\0\1\4\1\130\4\4\7\0\13\4\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2310];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\2\11\1\1\2\11\5\1\7\11"+
    "\10\1\1\0\1\1\3\11\1\0\1\11\16\1\4\0"+
    "\13\1\1\11\2\0\11\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
public Symbol newSymbol(int tokenId, Object value){
	return new Symbol(tokenId, yyline, yycolumn, value);
}
public Symbol newSymbol(int tokenId){
	return new Symbol(tokenId, yyline, yycolumn);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
 * @throws YeledCompilerException 
   */
  public Symbol next_token() throws java.io.IOException, YeledCompilerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { return newSymbol(sym.ATRIBUICAO);
          }
        case 41: break;
        case 36: 
          { return newSymbol(sym.KEY_PRINT);
          }
        case 42: break;
        case 1: 
          { // Casa com qualquer caracter que não possui nenhuma regra acima.
        	  	throw new YeledCompilerException("Caractere ilegal: " + yytext(), yyline, yycolumn); // lanca excecao de caractere invalido
          }
        case 43: break;
        case 23: 
          { return newSymbol(sym.MAIOR_OU_IGUAL);
          }
        case 44: break;
        case 24: 
          { return newSymbol(sym.DIFERENTE_QUE);
          }
        case 45: break;
        case 37: 
          { // regra para comentarios de varias linhas
										// Comentários multi-linhas.
										// Não retorna token.
          }
        case 46: break;
        case 5: 
          { return newSymbol(sym.MENOR_QUE);
          }
        case 47: break;
        case 13: 
          { return newSymbol(sym.ABRE_PAR);
          }
        case 48: break;
        case 21: 
          { return newSymbol(sym.MENOR_OU_IGUAL);
          }
        case 49: break;
        case 26: 
          { return newSymbol(sym.OR);
          }
        case 50: break;
        case 7: 
          { return newSymbol(sym.MAIOR_QUE);
          }
        case 51: break;
        case 15: 
          { return newSymbol(sym.VIRGULA);
          }
        case 52: break;
        case 25: 
          { // regra para comentarios de apenas uma linha
										// Comentários de linha.
										// Não retorna token.
          }
        case 53: break;
        case 3: 
          { return newSymbol(sym.IDENTIFICADOR, yytext());
          }
        case 54: break;
        case 8: 
          { return newSymbol(sym.SOMA);
          }
        case 55: break;
        case 14: 
          { return newSymbol(sym.FECHA_PAR);
          }
        case 56: break;
        case 16: 
          { return newSymbol(sym.PONTO_VIRGULA);
          }
        case 57: break;
        case 20: 
          { return newSymbol(sym.FLOAT_LITERAL, yytext());
          }
        case 58: break;
        case 29: 
          { return newSymbol(sym.NOT);
          }
        case 59: break;
        case 28: 
          { return newSymbol(sym.AND);
          }
        case 60: break;
        case 18: 
          { return newSymbol(sym.ABRE_CHAVE);
          }
        case 61: break;
        case 30: 
          { return newSymbol(sym.KEY_INT);
          }
        case 62: break;
        case 11: 
          { return newSymbol(sym.DIV);
          }
        case 63: break;
        case 35: 
          { return newSymbol(sym.KEY_VOID);
          }
        case 64: break;
        case 9: 
          { return newSymbol(sym.SUB);
          }
        case 65: break;
        case 27: 
          { return newSymbol(sym.KEY_IF);
          }
        case 66: break;
        case 33: 
          { return newSymbol(sym.KEY_ELSE);
          }
        case 67: break;
        case 12: 
          { return newSymbol(sym.RESTO);
          }
        case 68: break;
        case 22: 
          { return newSymbol(sym.IGUAL_QUE);
          }
        case 69: break;
        case 32: 
          { return newSymbol(sym.KEY_THEN);
          }
        case 70: break;
        case 40: 
          { return newSymbol(sym.KEY_RETURN);
          }
        case 71: break;
        case 2: 
          { // executa o bloco quando lido um espaco em branco
											// Caracteres ignorados.
											// Nenhum token é retornado.
          }
        case 72: break;
        case 39: 
          { return newSymbol(sym.KEY_WHILE);
          }
        case 73: break;
        case 34: 
          { return newSymbol(sym.KEY_CHAR);
          }
        case 74: break;
        case 17: 
          { return newSymbol(sym.DOIS_PONTOS);
          }
        case 75: break;
        case 31: 
          { return newSymbol(sym.CHAR_LITERAL, yytext());
          }
        case 76: break;
        case 38: 
          { return newSymbol(sym.KEY_FLOAT);
          }
        case 77: break;
        case 4: 
          { return newSymbol(sym.INT_LITERAL, yytext());
          }
        case 78: break;
        case 19: 
          { return newSymbol(sym.FECHA_CHAVE);
          }
        case 79: break;
        case 10: 
          { return newSymbol(sym.MULT);
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                // Casa com o fim do arquivo apenas.
	return newSymbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
